# Generated by Django 4.2.4 on 2023-08-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='track_id',
            new_name='track',
        ),
    ]
